# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JPE6zaC/uWpNsbvxxkaaUpc4yeQFR7Pssq+os+rZBbxnoldNJCoz6tdNsi3dMOOBiaZ1te/SVTspjqwDVUB3oBeJv/CplIjMA/s3sAvLl8syYguwh6fYNyfwKSTicVXAAq3bw3UUpEnrRFeCU6uan4wuqziuti9l3GRJ70ATkKrByY13mzBIOV2vNKAeynywYiumW24OsLId29yEpT3YgIcg1FJb8nhViSBiN0/edIBTCaB0UwFKV3L0OV5AsrAB7VyKGsDdOjzDK7Z9tCk8VonKKixTru6sitfUdm0EiKhcdMg0W6GxmMezMiGQ+2L3uZ4nUFVNyl5Ney7RefFgUQQ3rUzSzgKFNRhXiOJvzKduMTiDyk+z6qajQSV/JQZGhbNJ+MzstmqePVhmYXRfLd/p2GbZGhZhq6iRov2Ioxkkz0CI3CeqXbUxasB0rCdHPhCNbfzsTEpRSaAewCHc4lPUIavnhWPwGpvoJfkWFwRdpM4aig4Q41kFzunvoR9/OLm54E7+Vw2+2Dz4kbjQMw8Tom9ma3t1s0yY3kZaJjTBehKpUm/9gKpvpoCOOF5gxfI6bo/iLQCvYEDed3VerJcCvvVmUo5yw0uFVsLxeUhPbPfhdtla9+Pn5v5XkH2cu+c0cWygHCE5kH14wwp2PLf7FtVPwaz1ZxAwqgCWFmk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
