travis:
  secure:
    BINSTAR_TOKEN: JPE6zaC/uWpNsbvxxkaaUpc4yeQFR7Pssq+os+rZBbxnoldNJCoz6tdNsi3dMOOBiaZ1te/SVTspjqwDVUB3oBeJv/CplIjMA/s3sAvLl8syYguwh6fYNyfwKSTicVXAAq3bw3UUpEnrRFeCU6uan4wuqziuti9l3GRJ70ATkKrByY13mzBIOV2vNKAeynywYiumW24OsLId29yEpT3YgIcg1FJb8nhViSBiN0/edIBTCaB0UwFKV3L0OV5AsrAB7VyKGsDdOjzDK7Z9tCk8VonKKixTru6sitfUdm0EiKhcdMg0W6GxmMezMiGQ+2L3uZ4nUFVNyl5Ney7RefFgUQQ3rUzSzgKFNRhXiOJvzKduMTiDyk+z6qajQSV/JQZGhbNJ+MzstmqePVhmYXRfLd/p2GbZGhZhq6iRov2Ioxkkz0CI3CeqXbUxasB0rCdHPhCNbfzsTEpRSaAewCHc4lPUIavnhWPwGpvoJfkWFwRdpM4aig4Q41kFzunvoR9/OLm54E7+Vw2+2Dz4kbjQMw8Tom9ma3t1s0yY3kZaJjTBehKpUm/9gKpvpoCOOF5gxfI6bo/iLQCvYEDed3VerJcCvvVmUo5yw0uFVsLxeUhPbPfhdtla9+Pn5v5XkH2cu+c0cWygHCE5kH14wwp2PLf7FtVPwaz1ZxAwqgCWFmk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
