travis:
  secure:
    BINSTAR_TOKEN: kxqpX4Q8akrwJvsTyDnltubH54uZTBn2JmlswRW72la1yXyOWjGLeOSEHI3J9oJ7aD175v+26ItV8cgGnLr5L7X7D2qwkQ1HWemEsnXabZF0DJQ3iMSmw4PrtacGYvex1wEURW7gfmf3wlUcnPSTkYITUUw1COQYNWwSBdKV/JE7KdmPW3ZodCGeQMvWvUL7vzVBRqIOA0vyXQ7AiOqX4Fg4Uy4pmsSSuPEeyrTR5tPI4QEuMPSgsvixL87s7kKn2mARVv7MWrYnGDjHJD2IsNNzHbvbaEYXKHwkEGlb4/oDRJcAP2oZPxlH9DFD4cc/D2jDgoU9L7RIpvooj4xFp68iK3w5uRmQQRt/QOHsvaYAiUbnU6SA6AvvU57JPO/COG2GRLxgFIk+GlNBGznocOYrfOuyiaGTa9uRTwXs3Ztyi4auX+7TbgCopVgzznZMtk4jyKFQ5qMfhXsQIVObqt+gpE12IYC90PFgSbrMRePJs6wmSNU9v6x3L5SSNNvkwvhvFxEBirlcj+6SRpkqc6tLhombbGOP/LT5FUhpGFKEP6C6g8iyeCcPB5epyAvJLwZLjRl+fPIdsqaEk2w1WQGYT3rlIG9DlhDEvhh1Mt5XEF80E6ne64U58YJmWTIFyBQhkXB//VUi9itcTKjoagUYsZngAbxmSteh/d+xdOI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
